services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    image: bookstore-backend-auth:latest
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  bookstores:
    build:
      context: .
      dockerfile: ./apps/bookstores/Dockerfile
      target: development
    image: bookstore-backend-bookstores:latest
    command: pnpm run start:dev bookstores
    env_file:
      - ./apps/bookstores/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres
    env_file: .env
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
