apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookstores
  name: bookstores
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstores
  template:
    metadata:
      labels:
        app: bookstores
    spec:
      containers:
        - image: '<ARTIFACT_REGISTRY_URI>/bookstores/production:latest'
          imagePullPolicy: Always
          name: bookstores
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: '3001'
